FROM ubuntu:22.04

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Used by running apps to detect if inside a docker container. Testing for existence of /.dockerenv may not always work.
ENV InDocker=True

RUN apt-get update && apt-get install -y apt-utils

# Run update again to work around git install failure introduced around April 2023
RUN apt-get update

RUN apt-get install -y \
        git \
        build-essential \
        libgpm2 \
        gnupg \
        wget \
        psmisc \
        libcurl4-openssl-dev \
        unixodbc-dev

RUN apt-get update && apt-get -y upgrade

# Had to run the following dependency install separatly
RUN apt-get install -y libssl-dev

# install Postgresql odbc driver
RUN apt-get -y install odbc-postgresql

# install harbour from src
RUN mkdir /src
WORKDIR /src
RUN git clone --branch master https://github.com/harbour/core.git harbour
WORKDIR /src/harbour

ENV HB_WITH_CURL=/usr/include/x86_64-linux-gnu/
ENV HB_WITH_OPENSSL=/usr/include/openssl/

# Will request the make app to use up to 8 core.
RUN make -j 8 install

#To fix symlinks
RUN ldconfig

# Make some additional supporting libs
WORKDIR /src
RUN git clone https://github.com/EricLendvai/Harbour_EL/
RUN git clone https://github.com/EricLendvai/Harbour_ORM/

#Will be used for future web apps builds and when building hb_orm
ENV HB_EL_ROOT /src/Harbour_EL
ENV HB_ORM_ROOT /src/Harbour_ORM

ENV HB_COMPILER gcc

ENV BuildMode release

WORKDIR /src/Harbour_EL
RUN chmod +x ./BuildLIB.sh
ENV LIBName hb_el
RUN ./BuildLIB.sh

WORKDIR /src/Harbour_ORM
RUN chmod +x ./BuildLIB.sh
ENV LIBName hb_orm
RUN ./BuildLIB.sh

#also build debug libraries
ENV BuildMode debug

WORKDIR /src/Harbour_EL
ENV LIBName hb_el
RUN ./BuildLIB.sh

WORKDIR /src/Harbour_ORM
ENV LIBName hb_orm
RUN ./BuildLIB.sh
